--
-- Script was generated by Devart dbForge Data Generator for MySQL, Version 2.4.526.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/data-generator
-- Script date 04.03.2022 14:32:45
-- Target server version: 8.0.23
-- Target connection string: User Id=root;Host=localhost;Database=db_employees;Character Set=utf8
--



SET NAMES 'utf8';
USE db_employees;
--
-- Delete data from the table 'jobs'
--
DELETE FROM jobs;
--
-- Delete data from the table 'departments'
--
DELETE FROM departments;

--
-- Inserting data into table departments
--
INSERT INTO departments(id, name) VALUES
(1, 'Executive'),
(2, 'Research and Development'),
(3, 'Facilities'),
(4, 'Manufacturing'),
(5, 'Customer Support'),
(6, 'Information Technology'),
(7, 'Marketing'),
(8, 'Sales'),
(9, 'Operations'),
(10, 'Consulting');

--
-- Inserting data into table jobs
--
INSERT INTO jobs(id, name) VALUES
(1, 'Vice President'),
(2, 'Computer Operator'),
(3, 'Travel Agent'),
(4, 'Application Development Supervisor'),
(5, 'Marketing Manager'),
(6, 'Application Engineer'),
(7, 'Technical Manager'),
(8, 'Assistant Vice President'),
(9, 'Service Manager'),
(10, 'QA Engineer'),
(11, 'Communication Consultant'),
(12, 'Senior Specialist'),
(13, 'Secretary'),
(14, 'Contract Manager'),
(15, 'Chief Technology Officer'),
(16, 'Contract Advisor'),
(17, 'Network Administrator'),
(18, 'Technical Specialist'),
(19, 'Area Administrator'),
(20, 'Finance Controller'),
(21, 'Senior Manager'),
(22, 'Commercial Director'),
(23, 'Senior Advisor'),
(24, 'Channel Sales Manager'),
(25, 'Sales Coordinator'),
(26, 'Solution Architect'),
(27, 'Branch Manager'),
(28, 'President'),
(29, 'Chief Financial Officer'),
(30, 'Support Manager');